# Generated by Django 4.2.7 on 2023-11-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='img',
        ),
    ]
